name: Build Next.js Static Site

on:
  workflow_dispatch: # allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies (no lockfile issue)
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Ensure no old "out" folder lingers
      - name: Clean old out folder
        run: rm -rf out

      # Build & export static site
      - name: Build static export
        run: |
          npm run build
          npm run export

      # Upload the new out folder
      - name: Upload out folder
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-out
          path: out
